<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PasienTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('pasien')->insert([
            [
                'nama_panjang' => 'Ahmad Fauzi',
                'tanggal_lahir' => '1989-11-05',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567901',
                'email' => 'ahmad.fauzi@example.com',
                'pekerjaan' => 'Petani',
                'alamat' => 'Jl. Sawah No. 1',
                'nomor_identitas' => '9876543210',
                'id_perawat' => 1,
                'id_dokter' => 6,
                'tanggal_pemeriksaan' => '2025-01-29',
                'waktu_pemeriksaan' => '08:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Maria Fransiska',
                'tanggal_lahir' => '1993-06-12',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567902',
                'email' => 'maria.fransiska@example.com',
                'pekerjaan' => 'Perawat',
                'alamat' => 'Jl. Anggrek No. 4',
                'nomor_identitas' => '1234598765',
                'id_perawat' => 2,
                'id_dokter' => 7,
                'tanggal_pemeriksaan' => '2025-01-30',
                'waktu_pemeriksaan' => '10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Gilang Saputra',
                'tanggal_lahir' => '1985-04-20',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567903',
                'email' => 'gilang.saputra@example.com',
                'pekerjaan' => 'Wiraswasta',
                'alamat' => 'Jl. Mangga No. 2',
                'nomor_identitas' => '3456712345',
                'id_perawat' => 3,
                'id_dokter' => 8,
                'tanggal_pemeriksaan' => '2025-01-31',
                'waktu_pemeriksaan' => '13:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Fitri Handayani',
                'tanggal_lahir' => '1996-03-15',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567904',
                'email' => 'fitri.handayani@example.com',
                'pekerjaan' => 'Mahasiswa',
                'alamat' => 'Jl. Cemara No. 6',
                'nomor_identitas' => '4567823456',
                'id_perawat' => 1,
                'id_dokter' => 9,
                'tanggal_pemeriksaan' => '2025-02-01',
                'waktu_pemeriksaan' => '09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Dedi Kurniawan',
                'tanggal_lahir' => '1987-09-10',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567905',
                'email' => 'dedi.kurniawan@example.com',
                'pekerjaan' => 'Pegawai Negeri',
                'alamat' => 'Jl. Kenari No. 8',
                'nomor_identitas' => '5678934567',
                'id_perawat' => 2,
                'id_dokter' => 10,
                'tanggal_pemeriksaan' => '2025-02-02',
                'waktu_pemeriksaan' => '14:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Sari Lestari',
                'tanggal_lahir' => '1990-12-22',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567906',
                'email' => 'sari.lestari@example.com',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'alamat' => 'Jl. Cempaka No. 5',
                'nomor_identitas' => '6789045678',
                'id_perawat' => 3,
                'id_dokter' => 6,
                'tanggal_pemeriksaan' => '2025-02-03',
                'waktu_pemeriksaan' => '08:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Rama Agustian',
                'tanggal_lahir' => '1995-07-07',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567907',
                'email' => 'rama.agustian@example.com',
                'pekerjaan' => 'Pelajar',
                'alamat' => 'Jl. Sakura No. 10',
                'nomor_identitas' => '7890156789',
                'id_perawat' => 1,
                'id_dokter' => 7,
                'tanggal_pemeriksaan' => '2025-02-04',
                'waktu_pemeriksaan' => '11:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Desi Andriani',
                'tanggal_lahir' => '1992-05-25',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567908',
                'email' => 'desi.andriani@example.com',
                'pekerjaan' => 'Karyawan Swasta',
                'alamat' => 'Jl. Mawar No. 3',
                'nomor_identitas' => '8901267890',
                'id_perawat' => 2,
                'id_dokter' => 8,
                'tanggal_pemeriksaan' => '2025-02-05',
                'waktu_pemeriksaan' => '15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Hendra Wijaya',
                'tanggal_lahir' => '1988-02-10',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567909',
                'email' => 'hendra.wijaya@example.com',
                'pekerjaan' => 'Akuntan',
                'alamat' => 'Jl. Flamboyan No. 5',
                'nomor_identitas' => '2345678901',
                'id_perawat' => 3,
                'id_dokter' => 6,
                'tanggal_pemeriksaan' => '2025-02-06',
                'waktu_pemeriksaan' => '10:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Intan Permata',
                'tanggal_lahir' => '1991-10-05',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567910',
                'email' => 'intan.permata@example.com',
                'pekerjaan' => 'Designer Grafis',
                'alamat' => 'Jl. Teratai No. 9',
                'nomor_identitas' => '1234567898',
                'id_perawat' => 1,
                'id_dokter' => 7,
                'tanggal_pemeriksaan' => '2025-02-07',
                'waktu_pemeriksaan' => '09:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Budi Raharjo',
                'tanggal_lahir' => '1983-11-15',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567911',
                'email' => 'budi.raharjo@example.com',
                'pekerjaan' => 'Konsultan',
                'alamat' => 'Jl. Melati No. 7',
                'nomor_identitas' => '5678901234',
                'id_perawat' => 2,
                'id_dokter' => 8,
                'tanggal_pemeriksaan' => '2025-02-08',
                'waktu_pemeriksaan' => '14:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Diana Amalia',
                'tanggal_lahir' => '1997-06-30',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567912',
                'email' => 'diana.amalia@example.com',
                'pekerjaan' => 'Content Creator',
                'alamat' => 'Jl. Duku No. 4',
                'nomor_identitas' => '2345678902',
                'id_perawat' => 3,
                'id_dokter' => 9,
                'tanggal_pemeriksaan' => '2025-02-09',
                'waktu_pemeriksaan' => '08:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Andi Wijaya',
                'tanggal_lahir' => '1986-05-25',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567913',
                'email' => 'andi.wijaya@example.com',
                'pekerjaan' => 'Dosen',
                'alamat' => 'Jl. Rambutan No. 6',
                'nomor_identitas' => '7890123456',
                'id_perawat' => 1,
                'id_dokter' => 10,
                'tanggal_pemeriksaan' => '2025-02-10',
                'waktu_pemeriksaan' => '11:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Putri Maharani',
                'tanggal_lahir' => '1994-09-18',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567914',
                'email' => 'putri.maharani@example.com',
                'pekerjaan' => 'Pengacara',
                'alamat' => 'Jl. Kamboja No. 3',
                'nomor_identitas' => '8901234567',
                'id_perawat' => 2,
                'id_dokter' => 6,
                'tanggal_pemeriksaan' => '2025-02-11',
                'waktu_pemeriksaan' => '13:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Reno Saputra',
                'tanggal_lahir' => '1990-12-05',
                'jenis_kelamin' => 'Laki-laki',
                'nomor_hp' => '081234567915',
                'email' => 'reno.saputra@example.com',
                'pekerjaan' => 'Arsitek',
                'alamat' => 'Jl. Angsana No. 2',
                'nomor_identitas' => '6789012345',
                'id_perawat' => 3,
                'id_dokter' => 7,
                'tanggal_pemeriksaan' => '2025-02-12',
                'waktu_pemeriksaan' => '15:45:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_panjang' => 'Siska Natalia',
                'tanggal_lahir' => '1998-03-08',
                'jenis_kelamin' => 'Perempuan',
                'nomor_hp' => '081234567916',
                'email' => 'siska.natalia@example.com',
                'pekerjaan' => 'Marketing',
                'alamat' => 'Jl. Pisang No. 9',
                'nomor_identitas' => '1234567897',
                'id_perawat' => 1,
                'id_dokter' => 8,
                'tanggal_pemeriksaan' => '2025-02-13',
                'waktu_pemeriksaan' => '09:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
